### ISSUE TITLE
Error opening file : file not found

### ISSUE THREAD

**Issue by Nickous** [jhass/nextcloud-keeweb#107]
Hello
Debian9
NginX

From Files App, if I select à kdbx file whose name (or folder) contains character "&", I've got an error message "File not found" :
![image](https://user-images.githubusercontent.com/10545977/59472382-801cd300-8e3e-11e9-96a8-0c3ae6eca56d.png)

In fact, everything after the "&" disappears!

Thanks

**Comment by CrysK** [comment]
Same here!
Ubuntu 14, apache2.

This only happens if the file is called from the nextcloud. A local file can be located in a folder with special characters.

**Comment by david-bla** [comment]
I can also confirm this issue.

**Comment by maurerle** [comment]
The file is not found as everything behind the first noted ampersand & is cut when regex replacing the fileinfo path:
https://github.com/jhass/nextcloud-keeweb/blob/d7ed6f301e1984afc87f2f5b98815cfd58d835ea/keeweb/js/script.js#L48
This happens because we decoded the URI before and have the path in plain:
https://github.com/jhass/nextcloud-keeweb/blob/d7ed6f301e1984afc87f2f5b98815cfd58d835ea/keeweb/js/script.js#L20

So we should have
`fileInfo.path =encodeURIComponent(fileInfo.path)`
before Line 48. Or make a oneliner from it.

**Comment by b90g** [comment]
> So we should have
> `fileInfo.path =encodeURIComponent(fileInfo.path)`
> before Line 48. Or make a oneliner from it.


making Line 48 into 49 and adding said code didn fix it for me... will continue to test

**Comment by b90g** [comment]
https://github.com/jhass/nextcloud-keeweb/blob/master/keeweb/lib/Controller/PageController.php#L50

Although the fix seem still to be applied, opening files within a folder containing an ampersand in folder name,  is not possible. 


I think it could be https://github.com/jhass/nextcloud-keeweb/blob/master/keeweb/src/viewer.js#L19

Made in https://github.com/jhass/nextcloud-keeweb/pull/235
