### ISSUE TITLE
Synchronizing from PC removes shared

### ISSUE THREAD

**Issue by tikoflano** [jhass/nextcloud-keeweb#109]
If I have **.kdbx** file shared in my NC and I open it form my PC, after syncrhonize it from the PC (hit `ctrl + s` for example) the shared options are gone and now every person who I shared the file has his own independant copy of it.

I have to create the **.kdbx** file in a group folder in order to avoid this, but it is not ideal.

**Comment by jhass** [comment]
That's because KeeWeb does an atomic update through the rename, write and delete strategy, that is writes the updated database to a new filename, then deletes the old and renames the newly written file to the old name.

I'm not sure that's something we can fix here short of asking upstream to gives us an option to disable this strategy in favor of the more dangerous directly overwriting the existing file.

**Comment by tikoflano** [comment]
OK, thanks for the quick response. So maybe using the groupfolders strategy isn't a bad option after all.

**Comment by tikoflano** [comment]
I realized that KeeWeb for PC has an option to update the database using a PUT request. When using this option the sharing configuration is maintained.
