### ISSUE TITLE
Implementation details

### ISSUE THREAD

**Issue by phsc** [jhass/nextcloud-keeweb#12]
I have some questions regarding nextcloud-keeweb, that are probably also of general interest and for whom I could not find an answer:
- How do you integrate/embed keeweb itself (index.html)?
- Can the user override the embedded keeweb?
- Do you connect to the .kdbx file via WebDAV or is this not needed because your app is integrated in Nextcloud and you connect to the .kdbx file somehow directly?
- How do you authenticate on the .kdbx file? Do you pass the Nextcloud credentials to the .kdbx file?

Thank you for a quick answer. :-)

**Comment by jhass** [comment]
> How do you integrate/embed keeweb itself (index.html)?

Yes, the app ships with a custom build of the upcoming Keeweb 1.3 which has a feature that makes the integration possible.

> Can the user override the embedded keeweb?

While one could replace the template file the app ships with some manual labor, I wouldn't recommend it and it won't become a user faced setting.

> Do you connect to the .kdbx file via WebDAV or is this not needed because your app is integrated in Nextcloud and you connect to the .kdbx file somehow directly?

Yes, Keeweb is preconfigured to open the file via WebDAV. Since Keeweb runs in the browser fully, anything else is not really possible and would require at least custom endpoints to return and receive raw file data, which I'd rather like to avoid as much as possible.

> How do you authenticate on the .kdbx file? Do you pass the Nextcloud credentials to the .kdbx file?

Not at all, you still have to enter the databases password to open it. If your database needs a keyfile you currently need to have that available locally, see #7.

**Comment by phsc** [comment]
You are great! Thanks for your quick reply!
