### ISSUE TITLE
update from 0.2.4 to 2.4.5 under nc 9.53 not automatic and brakes integry check

### ISSUE THREAD

**Issue by JSoko** [jhass/nextcloud-keeweb#13]
Thank You for 0.25

I run nc 9.53 under ubuntu 16.04 lts and apache2 on odroid xu4

The update isn't done automaticaly; I think that's because the app is only in the Nc- and not in the Oc-Appstore.

After Upgrading manually the Nc updateprocess runs.
Afterwards I've got an intergry-check error concerning the .htaccess
Had to fix it with
'integrity.check.disabled' => true,
in config.php
rescan for integry check
and set 
'integrity.check.disabled' => true,
again.

**Comment by jhass** [comment]
Yes, it doesn't automatically update for now.

I'm reluctant to commit to supporting Owncloud since I'll use Nextcloud only myself. Nextcloud 9 and 10 do and will still use Ownclouds appstorre, Nextcloud 11 expected around December will use their new appstore and then automatic updates should start working.

I see no possible way in which this plugin could touch anything that would fail the integrity check, I think this is an issue with Nextcloud or your installation rather than this plugin, merely surfaced through the update triggering the updater and thus the integrity check.

**Comment by JSoko** [comment]
No problem...
...just wantet to inform you.
