### ISSUE TITLE
⚠ Looking for maintainers ⚠

### ISSUE THREAD

**Issue by thomas-mc-work** [jhass/nextcloud-keeweb#151]
Hello users and developers!

Some of you might have noticed that @jhass, the official owner of this project, doesn't feel able to maintain this project anymore. See this little conversation about that:

https://github.com/jhass/nextcloud-keeweb/pull/148#issuecomment-651213826

It would be great to find a small group of people, who would like to take over this project. This shall happen in a newly created dedicated project. This steps shall emphasize the independence of the current (then former) project maintainer.

__What is expected from a candidate?__

Well, I think not too much. The most important goal would be to keep this project compatible to the latest releases of Nextcloud. Also, some bug fixing or support in the issues would be great. Everything else is optional and totally up to you … but still much appreciated!

__So finally it'd be lovely to hear from you in the comments!__

**Comment by jhass** [comment]
Note this post is done without my consent or input.

**Comment by maurerle** [comment]
Actually I don't feel like he "doesn't feel able to maintain" the project. He takes care of the code which gets published and manages what gets released but does not have time to put a lot of effort into new features and testing which is understandable and I could not do a lot more either.

The problem is not that noone could fork it. I think there are a few occasional contributers who try to help but also don't have the time to be the lead maintainer for this project.

If someone would 
* add a "new keepass file" entry from the files menu
* manages a way to include the languages from the plugins and load them according to the user language set in NC
* makes sure that the light/dark theme option in NC is passed to the Keeweb Application

then this would be great, but everyone could just file a PR for this and you don't need a new maintainer for this.
Currently nothing is stopping anyone from improving the code and @jhass is reacting quite well if needed, so I don't think that this repo should be activly searching for a new maintainer if it is not inteded by him in the first place.

**Comment by thomas-mc-work** [comment]
> Actually I don't feel like he "doesn't feel able to maintain" the project. He takes care of the code which gets published and manages what gets released but does not have time to put a lot of effort into new features and testing which is understandable

I took my motivation for this issue from this comment of @jhass:

> I'm as always hesitant to actually release this because of the overall brokenness of this addon, and to be honest I don't feel like having either the in-depth knowledge of Nextcloud nor the motivation to acquire such to give it the attention it might deserve. So if y'all know somebody that does or feel like you do, let's talk :)

If my effort is not desired by him then I'm fine with just closing this issue. It's not my intention to provoke annoyance. It'd just be a pity to see this app slowly starving.
