### ISSUE TITLE
Share password with one time valid link

### ISSUE THREAD

**Issue by jpsarda** [jhass/nextcloud-keeweb#173]
Is there a way to share a password to someone else with a one time valid link ? That would be really awesome, that's the only thing I'm missing in this app.

[edit] I lied there is one thing I miss too, it's a shortcut to synchronize my changes.

**Comment by arnowelzel** [comment]
No - this is not possible.

Keeweb only runs in your browser only, loads the Keepass database and decrypts it in memory after you have entered your password for it (this is also true for https://app.keeweb.info/ - the server there never gets your database and the app only runs in your browser).

Sharing anything from it would require the server to decrypt the datatabase and read the shared record so someone can read that information using a link. However this would fundamentally break security since the whole idea of Keeweb is **not** to open the database on the server.

Keeweb itself also does not provide such a feature, neither does any other Keepass implementation I know.

With KeepassXC you can establish shared databases, however this requires to use the desktop or mobile application, see https://keepassxc.org/docs/KeePassXC_UserGuide.html#_database_sharing_with_keeshare. Theoretically you can use a public shared Nextcloud folder to keep the Keeshare files, however in my tests it turned out not to be very reliable. Maybe this has changed over the time.

Having a "share something using a one time valid link" is more a feature request for Nextcloud itself. This had been requested in the past, but not implemented yet because the idea behind a "one time link" makes not really sense to improve security: https://github.com/nextcloud/server/issues/6841

The better way to share passwords is using a secure channel like Signal.

**Comment by jpsarda** [comment]
Thx very much.
