### ISSUE TITLE
nextcloud 21 error

### ISSUE THREAD

**Issue by franconianmetal** [jhass/nextcloud-keeweb#181]
keeweb-addon works for me with nextcloud
  - installed: true
  - version: 20.0.8.1
  - versionstring: 20.0.8

  **- keeweb: 0.6.5**

Once upgrading to nextcloud 21.0.1 (not changing anything else) with
`sudo -u www-data php /var/www/nextcloud/updater/updater.phar`

I get an error
**"network error"**
when i want to open a kdbx-file like I do usually

https is set:
  'overwriteprotocol' => 'https',
  'forcessl' => true,

**Comment by arnowelzel** [comment]
Can you provide log files from Apache (error.log) and Nextloud?

**Comment by franconianmetal** [comment]
[error.log](https://github.com/jhass/nextcloud-keeweb/files/6301852/error.log)
[nextcloud.log](https://github.com/jhass/nextcloud-keeweb/files/6301853/nextcloud.log)

**Comment by arnowelzel** [comment]
The Apache log only contains messages about a restart from today. There is no indication about any error at all.

In the Nextcloud log I can see that there is a WebDAV error caused by some problem with SMB originating from `Icewind\SMB\\Native\NativeReadStream::stream_read`. Do you use external drives via SMB/CIFS? If yes, please check if it works when you move the Keepass file to an "internal" file storage on the Nextcloud server itself. Maybe there is a problem with the SMB/CIFS connection.

I also checked Keepass here - it works fine on Nextcloud 21.0.1 without any issues.

**Comment by franconianmetal** [comment]
accessing kdbx-file from normal nextcloud storage is fine.
accessing kdbx-file via smb-connected folder fails with "network-error".
accessing other files via smb-connected folder is works

**Comment by arnowelzel** [comment]
Thanks for confirmation of the issue. I have no idea yet what is wrong, but I'll try to verify this in a local test enviroment.

**Comment by franconianmetal** [comment]
Thanks Arno,
if you need to have any further logs or information pls reply.

**Comment by franconianmetal** [comment]
I reversed to 20.0.8 for productive usage.
meanwhile I was offered to update to nextcloud 20.0.9.
same problem when accessing kdbx via smb.

I have to stay with 20.0.8

**Comment by franconianmetal** [comment]
I tried hard an experimental VMs to exchange password-files, but finally ended in the problem what the update of icewind brought,
as well found in the error log -> "read-error"
Seems to be a general issue:
https://github.com/nextcloud/server/issues/26457
close this ticket here, cause not related to keeweb

**Comment by arnowelzel** [comment]
Thanks for the info.
