### ISSUE TITLE
Starting the app results in blank page and PHP Fatal error

### ISSUE THREAD

**Issue by didierm** [jhass/nextcloud-keeweb#30]
(possibly related to issue #26 ?)

After installing and activating the app (v0.2.9) on Nextcloud (v10.0.1), consulting its page (/index.php/apps/keeweb/) or clicking on a *.kdbx file yields an empty page, and the following PHP error : 

`PHP Fatal error:  Cannot redeclare class OC\Config in /usr/share/nextcloud/lib/private/Config.php on line 41`

**Comment by jhass** [comment]
I'm unsure how the app could possibly cause that, are you sure it's not a general issue of your setup?

**Comment by Yamakasi** [comment]
I'm having the same as reported after supporting NC11 in #33

**Comment by jhass** [comment]
@Yamakasi try 0.3.0, the changes #33 unfortunately weren't quite correct.

**Comment by Yamakasi** [comment]
@jhass I have that version (0.3.0) installed after your commit yesterday and it happens to stay blank.

**Comment by jhass** [comment]
> Try clearing your cache. Make sure you see the right version number when accessing `/index.php/apps/keeweb/manifest.appcache`.
https://github.com/jhass/nextcloud-keeweb/issues/32#issuecomment-267815785

**Comment by Yamakasi** [comment]
Hi should have been some cache I believe. Maybe it's good to tell in the docs you really need to empty then because ctrl + f5 doesn't fix it (have been there before).

Thanks! Noe we only need local storage usage without webdav :)

**Comment by Yamakasi** [comment]
I already see where it doesn't work, the latest Chromium shows a blank page and that where I use it as dekstop app.

Firefox works well, and Chromium was working on 0.2.9 with NC10

**Comment by jhass** [comment]
Works just fine for me on Chromium. Please check your error consoles.

**Comment by Yamakasi** [comment]
@jhass: this is what I see, is this a cache issue ?

`Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'nonce-dXVJaERWb0o4bmVicFdTcE5QdnhRdFcyN0M1L2ZVeVhYTHFqOCtVMkV1RT06d0xoemUyTkdpRHlya2wzQ1ZZcmVHNDMweDM0b0N6VzRFNHJ1a001QVI0bz0=' 'unsafe-inline' 'unsafe-eval'". Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.`

`Application Cache Error event: Manifest changed during update`

**Comment by jhass** [comment]
It looks like it, yes.

**Comment by Yamakasi** [comment]
@jhass Oh this is very wrong from me, I'm switching over to Chromium and didn't emty all cache yet, only last hour(s).

I should get some more sleep I guess as I'm kinda busy and making NextCloud my perfect tool! This tool helps with it ! Thanks!

**Comment by jfmcbrayer** [comment]
I have this error, with 0.2.9 in NC 10.0.4 (would update, but that seems to be the latest version of nextcloud-keeweb supported on NC 10, and I'm sticking with the NC version in my distro repositories).  I get this error:

> {PHP} Cannot declare class OC\Config, because the name is already in use at /usr/share/nextcloud/lib/private/Config.php#41

Can't look at `/index.php/apps/keeweb/manifest.appcache`, because that produces the same blank page and the same error in the logs.

**Comment by jhass** [comment]
Please leave a comment if this is still an issue for anybody. Until then closing.
