### ISSUE TITLE
Theme Defaults

### ISSUE THREAD

**Issue by Brailyn** [jhass/nextcloud-keeweb#70]
Is there a way to change the theme defaults so they are kept on the server side rather than the browser side?

**Comment by jhass** [comment]
The server side config (https://github.com/keeweb/keeweb/wiki/Configuration#json-app-config) is defined here https://github.com/jhass/nextcloud-keeweb/blob/master/keeweb/controller/pagecontroller.php#L84-L94

**Comment by Brailyn** [comment]
I don't know much about PHP, what is the correct syntax to add settings to L85?

`'settings' => (object) null,` 

Assuming config is default unless otherwise specified... What is the syntax to add the following?

`theme:"te", tableView:"true"`

**Comment by Subkrys** [comment]
hi I'm also interested about the right syntax, I'd be happy to find a way to configure the defaults settings

**Comment by hmdd81** [comment]
How did you manage that?

**Comment by robin-moser** [comment]
Just use something like this config in https://github.com/jhass/nextcloud-keeweb/blob/master/keeweb/controller/pagecontroller.php#L79-L89
```php
$config = [
	'settings' => [
		'theme' => 'fb',
		'locale' => 'de',
		'expandGroups' => 'false',
		'idleMintes' => 30
	],
	'files' => [
		[
			'storage' => 'webdav',
			'name' => $file.' on '.$this->request->getServerHost(),
			'path' => $this->joinPaths($webdavBase, $file.'?requesttoken='.urlencode($csrfToken)),
			"options" => ['user' => null, 'password' => null]
		]
	]
];

```

**Comment by CoplandTech** [comment]
Hi, I wanted to use the application settings through the pagecontroller, but nothing came of it. My code is this:
`$config = [
	'settings' => [
		'theme' => 'fb',
		'locale' => 'de',
	],`
Changes do not apply.
What to do? And if you know, tell me where to create the config.json file.

**Comment by maurerle** [comment]
Hello @CoplandTech 
i just figured it out myself.
Changing settings of the file `nextcloud/custom_apps/keeweb/controller/pagecontroller.php` does work.
But there is a bug in the code which prevents to load the config when starting the application.

As seen in https://github.com/jhass/nextcloud-keeweb/blob/380e78ffbc21d3edaf8b10dc0132ccc708df46a3/keeweb/controller/pagecontroller.php#L40-L42 the config is only loaded when open is specified, which is the case when opening an existing file from nextcloud.
Otherwise the config is currently not loaded.

You can patch this by implementing the changes from my pull request #121

**Comment by maurerle** [comment]
I just played around a little more. It is necessary to hit the LCID (Language Code identifier) for keeweb. So for german it is `de-DE` and not just de, while it ist en for english and pl for polish for example

For debugging purpose you can go to your keeweb app and hit F12 -> Web-Storage -> Local Storage and view your current `appSettings`

**Comment by CoplandTech** [comment]
I'm going to play with that today, too. In case of success esnosts or failures - I will write.
